version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3316:3306'
    volumes_from:
      - datastore

  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/rails_starter
    ports:
      - "3035:3035"

  phpmyadminserver:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8080:80

  datastore:
    image: busybox
    volumes:
      - rails_starter:/var/lib/mysql

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails_starter
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker

volumes:
  rails_starter:
    driver: local
