version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: admin
    env_file:
      - ./.env
    ports:
      - '3316:3306'
    volumes_from:
      - datastore

  phpmyadminserver:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8080:80

  datastore:
    image: busybox
    volumes:
      - rails_starter:/var/lib/mysql

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails_starter
      - bundle-starter:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  rails_starter:
    driver: local
  bundle-starter:
    driver: local
